### ISSUE TITLE
Better error for failure to create repositories

### ISSUE THREAD

**Issue by atheobold** [rundel/ghclass#68] opened 2019-08-14 21:59 UTC
The 422 error when creating repositories is not the most helpful. Surfacing why the error is occurring would be lovely! For example, I received the following error when attempting to create team repositories: 

```
Failed to create repo 'stat-511-section-001/lab01-team01'.
  [Error: GitHub API error (422): 422 Unprocessable Entity]
```

The following code surfaced that this error was due to my account's access to writing private repositories: 

```
res = httr::POST(
"https://api.github.com/orgs/stat-511-section-001/repos",
httr::add_headers(
          Authorization = paste("Bearer", ghclass::github_get_token())
     ),
encode = "json",
body = list(
         name = "lab01-team01",
         private = TRUE,
         auto_init = FALSE,
        gitignore_template = "R"
      )
)

str(httr::content(res))
List of 2
$ message          : chr "Visibility can't be private. Please upgrade your subscription to create a new private repository."
$ documentation_url: chr "https://github.com/pricing"
```

**Comment by mine-cetinkaya-rundel** [comment] 2019-08-14 22:01
Thank you @atheobold for the report! We will work on surfacing these errors, they would indeed be helpful for deciphering what the issue is, and specifically, whether the issue is resulting from errors in package code, errors in specified parameters, or something else the user has control over (like here).

**Comment by rundel** [comment] 2019-08-15 10:33
I think I've revised the error handling code so that we get a much more useful message out. Now a failed `repo_create` should look something like the following:

```
> repo_create("ShinyEd","hello")
✖ Failed to create repo 'ShinyEd/hello'.
  GitHub API error (422): 422 Unprocessable Entity
  └─ Visibility can't be private. Please upgrade your subscription to create a
     new private repository. (See https://github.com/pricing)
```

I'm going to close the issue for now, but if you have questions or comments please let us know.

**Closed by rundel** 2019-08-15 10:33 UTC
